"""Amendment 4 results -> figs/recast_numbers5.tex (macros for the revised paper; do not edit the .tex by hand).
Inputs: amend4_results.json (analyze_amend4.py) and ctc_mechanism.json (analyze_ctc_mechanism.py)."""
import json, pathlib
import numpy as np
H = pathlib.Path(__file__).resolve().parent
A = json.load(open(H / "amend4_results.json")); C = json.load(open(H / "ctc_mechanism.json"))
lines = ["% Generated by exposure/make_macros5.py; do not edit by hand."]
def s(x): return f"{x:+.3f}"          # signed contrast
def u(x): return f"{x:.3f}"           # unsigned WER
def m(name, val): lines.append(f"\\newcommand{{\\{name}}}{{{val}}}")
def ci(name, t, f=s): m(name, f(t[0])); m(name + "Lo", f(t[1])); m(name + "Hi", f(t[2]))

# F2 fresh reciters (RB contrast at k=4)
for key, tag in [("tarteel", "Tar"), ("M0", "Mz"), ("M1", "Mo"), ("M2", "Mt")]:
    ci(f"FrRb{tag}", A[f"F2_{key}"]["rb4"])
own = [A[f"F2_{k}"] for k in ("M0", "M1", "M2")]
m("FrRbMin", s(min(o["rb4"][0] for o in own))); m("FrRbMax", s(max(o["rb4"][0] for o in own)))
m("FrLoMin", s(min(o["rb4"][1] for o in own)))
allrec = [x for k in ("tarteel", "M0", "M1", "M2") for x in A[f"F2_{k}"]["per_reciter_rb4"]]
m("FrRecMin", s(min(allrec))); m("FrRecMax", s(max(allrec)))
m("FrCleanMin", u(min(A[f"F2_{k}"]["clean"][0] for k in ("tarteel", "M0", "M1", "M2"))))
m("FrCleanMax", u(max(A[f"F2_{k}"]["clean"][0] for k in ("tarteel", "M0", "M1", "M2"))))
m("FrN", A["F2_M0"]["n"])

# F1 seeds
rb = {v: [A[f"F1_{v}_s{i}"]["rb4"] for i in (1, 2, 3)] for v in ("M1", "M2")}
cl = {v: [A[f"F1_{v}_s{i}"]["clean"][0] for i in (1, 2, 3)] for v in ("M1", "M2")}
pts = [t[0] for v in rb for t in rb[v]]
m("SeedRbMin", s(min(pts))); m("SeedRbMax", s(max(pts))); m("SeedLoMin", s(min(t[1] for v in rb for t in rb[v])))
m("SeedSdMo", u(np.std([t[0] for t in rb["M1"]], ddof=1))); m("SeedSdMt", u(np.std([t[0] for t in rb["M2"]], ddof=1)))
m("SeedExpDiff", s(np.mean([t[0] for t in rb["M2"]]) - np.mean([t[0] for t in rb["M1"]])))
m("SeedRange", u(max(np.ptp([t[0] for t in rb[v]]) for v in rb)))
m("SeedCleanMo", u(np.mean(cl["M1"]))); m("SeedCleanMt", u(np.mean(cl["M2"])))
m("SeedCleanDiff", s(np.mean(cl["M2"]) - np.mean(cl["M1"])))
m("SeedCleanRange", u(max(np.ptp(cl[v]) for v in cl)))

sa, sc = A["F1_seedavg_M2_minus_M1_rb4"]["diff"], A["F1_seedavg_M2_minus_M1_clean"]["diff"]
m("SeedExpDiffLo", s(sa[1])); m("SeedExpDiffHi", s(sa[2])); m("SeedCleanDiffLo", s(sc[1])); m("SeedCleanDiffHi", s(sc[2]))

# F3 CTC recogniser (confirmatory reciters)
ci("CtcRb", C["F3a_rb4"]); ci("CtcGrowth", C["F3b_growth"])
m("CtcRbTwo", s(C["F3_rb2"][0])); m("CtcRbSix", s(C["F3_rb6"][0])); m("CtcPvTwo", s(C["F3_pv2"][0])); m("CtcClean", u(C["F3_clean"][0]))

# F4 Whisper-large-v3
v = A["F4_large_v3"]
ci("VthClean", v["clean"], u); ci("VthRb", v["rb4"]); ci("VthPv", v["pv4"])

# F5 English read speech
for key, tag in [("wav2vec2", "Wv"), ("whisper_base", "Wb")]:
    e = A[f"F5_{key}"]
    m(f"En{tag}Clean", u(e["clean"][0]))
    ci(f"En{tag}Rb", e["rb4"]); ci(f"En{tag}Bias", e["bias2"]); ci(f"En{tag}Growth", e["growth"])
    m(f"En{tag}RbTwo", s(e["rb2"][0])); m(f"En{tag}RbSix", s(e["rb6"][0])); m(f"En{tag}PvTwo", s(e["pv2"][0]))
    m(f"En{tag}RtPvG", u(e["rt_global_rt"][0])); m(f"En{tag}RtPvL", u(e["rt_nucleus_rt"][0]))
m("EnRtRbHiMax", u(max(A[f"F5_{k}"][f"rt_{a}"][2] for k in ("wav2vec2", "whisper_base") for a in ("global_rt_rb", "nucleus_rt_rb"))))
m("EnN", A["F5_wav2vec2"]["n_utts"])

# M mechanism (8 cells: 4 models x k in {2,4}); expected Spearman if only the k split orders the cells
import itertools, collections
m("MechRho", f"{C['M_spearman']:.2f}")
imb = {k: [c[2] for c in C["M_cells"] if c[1] == k] for k in (2.0, 4.0)}
m("MechImbTwoMin", f"{min(imb[2.0]):.2f}"); m("MechImbTwoMax", f"{max(imb[2.0]):.2f}")
m("MechImbFourMin", f"{min(imb[4.0]):.2f}"); m("MechImbFourMax", f"{max(imb[4.0]):.2f}")
split = [np.corrcoef(list(range(8)), list(p) + [4 + i for i in q])[0, 1] for p in itertools.permutations(range(4)) for q in itertools.permutations(range(4))]
m("MechRhoSplit", f"{np.mean(split):.2f}")

# post hoc sensitivity: reciter-level t intervals (per-reciter means, df = n-1)
from scipy import stats as st
def per_reciter(run, names):
    d = collections.defaultdict(dict)
    for l in open(H / "results" / run / "observations.jsonl"):
        r = json.loads(l)
        if r["kind"] == "condition" and r["reciter"] in names: d[(r["reciter"], r["verse"])][(r["arm"], r["k"])] = r["whisper"]["wer"]
    return [np.mean([row[("nucleus_rb", 4.0)] - row[("global_rb", 4.0)] for (n, v), row in d.items() if n == rc]) for rc in names]
def tint(x):
    x = np.array(x); se = x.std(ddof=1) / np.sqrt(len(x)); q = st.t.ppf(.975, len(x) - 1); return [x.mean(), x.mean() - q * se, x.mean() + q * se]
ci("TintFrMt", tint(per_reciter("fresh_M2", ["SahlYassin", "AkramAlalaqimy", "MuhsinAlQasim"])))
ci("TintVth", tint(per_reciter("large_v3", ["Alafasy", "Sudais", "Shuraym", "Dussary", "Rifai"])))

# post hoc control: boundary-blended local arm (PV, k=4) minus plain local, equal-reciter means, max over 4 models
def blend(run):
    d = collections.defaultdict(dict)
    for l in open(H / "results" / run / "observations.jsonl"):
        r = json.loads(l)
        if r["kind"] == "condition" and r["reciter"] in ["Alafasy", "Sudais", "Shuraym", "Dussary", "Rifai"]: d[(r["reciter"], r["verse"])][(r["arm"], r["k"])] = r["whisper"]["wer"]
    return np.mean([np.mean([row[("nucleus_edge", 4.0)] - row[("nucleus", 4.0)] for (n, v), row in d.items() if n == rc]) for rc in ["Alafasy", "Sudais", "Shuraym", "Dussary", "Rifai"]])
m("BlendMax", u(max(abs(blend(r)) for r in ("tarteel", "M0", "M1", "M2"))))

out = H / "figs" / "recast_numbers5.tex"; out.write_text("\n".join(lines) + "\n")
print(out, len(lines) - 1, "macros")
