"""Round-2 review analyses -> figs/recast_numbers4.tex (paper crossed bootstrap unless stated)."""
import json, collections, sys, pathlib, math
import numpy as np
H = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(H.parent / "confirmation")); sys.argv = ["x"]
import analyze_confirmation as A
P = ["Alafasy", "Sudais", "Shuraym", "Dussary", "Rifai"]; EXPL = ["AbdulBasit", "Husary", "Minshawy"]
MODELS = [("tarteel", "Tar"), ("M0", "Mz"), ("M1", "Mo"), ("M2", "Mt")]
def rows(m, recs=P, cap=None):
    d = collections.defaultdict(dict)
    for pre in ("", "rt_", "dose_"):
        f = H / "results" / f"{pre}{m}" / "observations.jsonl"
        for l in open(f):
            r = json.loads(l)
            if r["kind"] == "condition" and r["reciter"] in recs:
                w = r["whisper"]["wer"]; d[(r["reciter"], r["verse"])][(r["arm"], r["k"])] = min(w, cap) if cap else w
    return d
def crossed(d, fn, other=None):
    prim = {}
    for n in P:
        vs, vals = [], []
        for (rc, v), row in sorted(d.items()):
            if rc != n: continue
            try: x = fn(row) - (fn(other[(rc, v)]) if other is not None else 0)
            except KeyError: continue
            vs.append(v); vals.append(x)
        prim[n] = {"verses": vs, "differences": vals}
    s = A.crossed_summary(prim, np.random.default_rng(A.SEED)); return s
C = lambda la, ga, k: (lambda r: r[(la, k)] - r[(ga, k)])
s3 = lambda v: f"{v:+.3f}".replace("-", "$-$"); f3 = lambda v: f"{v:.3f}"
out = {}
def put(name, s):
    out[name] = s3(s["mean"]); out[name + "Lo"] = s3(s["ci95"][0]); out[name + "Hi"] = s3(s["ci95"][1])
lo_ranges, capdiff, pooldiff, rbpv = [], [], [], {}
for m, t in MODELS:
    d = rows(m)
    for k, kt in [(2.0, "Two"), (4.0, "Four")]:
        s = crossed(d, lambda r, k=k: C("nucleus_rb", "global_rb", k)(r) - C("nucleus", "global", k)(r)); put(f"RbMinusPv{kt}{t}", s)
        rbpv[(m, k)] = s
    s = crossed(d, C("nucleus_rb", "global_rb", 4.0)); loo = list(s["leave_one_reciter_out"].values()); lo_ranges += loo
    out[f"LooMin{t}"] = f"{min(loo):.3f}"; out[f"LooMax{t}"] = f"{max(loo):.3f}"
    per = [np.mean([row[("nucleus_rb", 4.0)] - row[("global_rb", 4.0)] for (n, v), row in d.items() if n == rc and ("nucleus_rb", 4.0) in row]) for rc in P]
    out[f"SignPos{t}"] = str(sum(x > 0 for x in per))
    dc = rows(m, cap=1.0); capdiff.append(abs(crossed(dc, C("nucleus_rb", "global_rb", 4.0))["mean"] - s["mean"]))
    # pooled (corpus-level) WER: errors / words, per reciter then mean
    put(f"Edge{t}", crossed(d, C("nucleus_edge", "global", 4.0)))
    de = rows(m, recs=EXPL)
    ex = [np.mean([row[("nucleus_rb", 4.0)] - row[("global_rb", 4.0)] for (n, v), row in de.items() if n == rc and ("nucleus_rb", 4.0) in row]) for rc in EXPL]
    out[f"Expl{t}"] = s3(float(np.mean(ex))); out[f"ExplPos{t}"] = str(sum(x > 0 for x in ex))
out["CapMaxDiff"] = f"{max(capdiff):.3f}"
out["SignP"] = f"{1/32:.3f}"
out["LooMinAll"] = f"{min(lo_ranges):.3f}"
m0, m1 = rows("M0"), rows("M1")
put("RbOneMinusZeroCI", crossed(m1, C("nucleus_rb", "global_rb", 4.0), other=m0))
# target statistics from the logged alignment (Tarteel run; identical across runs)
nint, share, dur, gl = [], [], [], {2: [], 4: [], 6: []}
for l in open(H / "results" / "tarteel" / "observations.jsonl"):
    r = json.loads(l)
    if r["kind"] == "alignment" and r["reciter"] in P:
        occ = r["occurrences"]; lens = [o["end_sample"] - o["start_sample"] for o in occ]
        N = r.get("samples") or r.get("n_samples")
        nint.append(len(occ)); dur += [x / 16000 * 1000 for x in lens]
        if N:
            share.append(sum(lens) / N)
            for k in gl: gl[k].append((N + sum(round((k - 1) * x) for x in lens)) / N)
out["IntMed"] = str(int(np.median(nint))); out["IntQl"] = str(int(np.percentile(nint, 25))); out["IntQh"] = str(int(np.percentile(nint, 75)))
out["DurMed"] = f"{np.median(dur):.0f}"
if share:
    out["ShareMed"] = f"{100*np.median(share):.0f}"
    for k in gl: out[f"GlobRatio{k}"] = f"{np.median(gl[k]):.2f}"
lines = ["% Generated by exposure/make_macros4.py; do not edit by hand."] + [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in out.items()]
(H / "figs" / "recast_numbers4.tex").write_text("\n".join(lines) + "\n")
for k, v in out.items(): print(k, v)
# capped-WER intervals and target share / implied global ratio (audio lengths from the manifest files)
import soundfile as sf
capped_lo = min(crossed(rows(m, cap=1.0), C("nucleus_rb", "global_rb", 4.0))["ci95"][0] for m, _ in MODELS)
man = json.load(open(H.parent / "confirmation" / "manifest_v2.json"))
paths = {(n, it["verse"]): it["path"] for n, g in man["reciters"].items() for it in g["files"]}
share, gl = [], {2: [], 4: [], 6: []}
for l in open(H / "results" / "tarteel" / "observations.jsonl"):
    r = json.loads(l)
    if r["kind"] == "alignment" and r["reciter"] in P:
        N = sf.info(paths[(r["reciter"], r["verse"])]).frames
        lens = [o["end_sample"] - o["start_sample"] for o in r["occurrences"]]
        share.append(sum(lens) / N)
        for k in gl: gl[k].append((N + sum(round((k - 1) * x) for x in lens)) / N)
extra = {"CappedMinLo": s3(capped_lo), "ShareMed": f"{100*np.median(share):.0f}",
         "GlobRatioTwo": f"{np.median(gl[2]):.2f}", "GlobRatioFour": f"{np.median(gl[4]):.2f}", "GlobRatioSix": f"{np.median(gl[6]):.2f}"}
with open(H / "figs" / "recast_numbers4.tex", "a") as fh:
    fh.write("\n".join(f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in extra.items()) + "\n")
print(extra)
fs = []
for m, _ in MODELS:
    d = rows(m); s = crossed(d, lambda r: C("nucleus_rb", "global_rb", 6.0)(r) - C("nucleus_rb", "global_rb", 4.0)(r)); fs.append((s["mean"], s["ci95"][0]))
with open(H / "figs" / "recast_numbers4.tex", "a") as fh:
    fh.write(f"\\newcommand{{\\FourSixMin}}{{{s3(min(x for x, _ in fs))}}}\n\\newcommand{{\\FourSixMax}}{{{s3(max(x for x, _ in fs))}}}\n")
print("k4->k6 steps", [(round(a,3), round(b,3)) for a, b in fs], "any lower bound > 0:", any(b > 0 for _, b in fs))
