"""Dose-response analysis (PROTOCOL.md Amendment 3): Delta_RB at k=2,4,6, growth 6 vs 2, RB round trip at k=2,6.
Writes figs/dose.json and figs/recast_numbers3.tex. Paper crossed bootstrap."""
import json, collections, sys, pathlib
import numpy as np
H = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(H.parent / "confirmation")); sys.argv = ["x"]
import analyze_confirmation as A
P = ["Alafasy", "Sudais", "Shuraym", "Dussary", "Rifai"]
MODELS = [("tarteel", "Tar"), ("M0", "Mz"), ("M1", "Mo"), ("M2", "Mt")]
def rows(m):
    d = collections.defaultdict(dict)
    for src in (H / "results" / m / "observations.jsonl", H / "results" / f"dose_{m}" / "observations.jsonl", H / "results" / f"rt_{m}" / "observations.jsonl"):
        for l in open(src):
            r = json.loads(l)
            if r["kind"] == "condition" and r["reciter"] in P:
                d[(r["reciter"], r["verse"])][(r["arm"], r["k"])] = r["whisper"]["wer"]
    return d
def crossed(d, fn):
    prim = {}
    for n in P:
        vs, vals = [], []
        for (rc, v), row in sorted(d.items()):
            if rc != n: continue
            try: vals.append(fn(row)); vs.append(v)
            except KeyError: pass
        prim[n] = {"verses": vs, "differences": vals}
    s = A.crossed_summary(prim, np.random.default_rng(A.SEED)); return [s["mean"], s["ci95"][0], s["ci95"][1]]
C = lambda k: (lambda r: r[("nucleus_rb", k)] - r[("global_rb", k)])
out = {"curve": {}, "six": {}, "two": {}, "growth": {}, "rt": {}}
for m, tag in MODELS:
    d = rows(m)
    for k in (2.0, 4.0, 6.0):
        out["curve"].setdefault(m, {})[str(k)] = crossed(d, C(k))
    out["two"][m] = out["curve"][m]["2.0"]; out["six"][m] = out["curve"][m]["6.0"]
    out["growth"][m] = crossed(d, lambda r: C(6.0)(r) - C(2.0)(r))
    out["rt"][m] = {f"{a}@{k}": crossed(d, lambda r, a=a, k=k: r[(a, k)] - r[("baseline", 1.0)]) for a in ("nucleus_rt_rb", "global_rt_rb") for k in (2.0, 6.0)}
out["rt_max_hi"] = max(v[2] for m in out["rt"] for v in out["rt"][m].values())
json.dump(out, open(H / "figs" / "dose.json", "w"), indent=1)
s3 = lambda v: f"{v:+.3f}".replace("-", "$-$")
own = ["M0", "M1", "M2"]
L = [f"\\newcommand{{\\RbTwoMin}}{{{s3(min(out['two'][m][0] for m in own))}}}", f"\\newcommand{{\\RbTwoMax}}{{{s3(max(out['two'][m][0] for m in own))}}}",
     f"\\newcommand{{\\RbSixMin}}{{{s3(min(out['six'][m][0] for m in own))}}}", f"\\newcommand{{\\RbSixMax}}{{{s3(max(out['six'][m][0] for m in own))}}}",
     f"\\newcommand{{\\RbSixTar}}{{{s3(out['six']['tarteel'][0])}}}", f"\\newcommand{{\\RbTwoTar}}{{{s3(out['two']['tarteel'][0])}}}",
     f"\\newcommand{{\\GrowthMin}}{{{s3(min(out['growth'][m][0] for m in own))}}}", f"\\newcommand{{\\GrowthMax}}{{{s3(max(out['growth'][m][0] for m in own))}}}",
     f"\\newcommand{{\\GrowthMinLo}}{{{s3(min(out['growth'][m][1] for m in own))}}}", f"\\newcommand{{\\RtRbDoseHi}}{{{out['rt_max_hi']:.3f}}}"]
(H / "figs" / "recast_numbers3.tex").write_text("% Generated by exposure/make_dose.py; do not edit by hand.\n" + "\n".join(L) + "\n")
for m, _ in MODELS:
    print(m, {k: [round(x, 3) for x in v] for k, v in out["curve"][m].items()}, "growth", [round(x, 3) for x in out["growth"][m]])
print("RB round-trip max upper bound at k=2,6:", round(out["rt_max_hi"], 3))
print("D1 (k=6 >0, M0-M2):", all(out["six"][m][1] > 0 for m in own), "| D2 (growth >0):", all(out["growth"][m][1] > 0 for m in own), "| D4 (<0.05):", out["rt_max_hi"] < 0.05)
worst = max(((m, k, v) for m in out["rt"] for k, v in out["rt"][m].items()), key=lambda t: t[2][2])
second = max((v[2] for m in out["rt"] for k, v in out["rt"][m].items() if (m, k) != (worst[0], worst[1])))
with open(H / "figs" / "recast_numbers3.tex", "a") as fh:
    fh.write(f"\\newcommand{{\\RtWorstPoint}}{{{worst[2][0]:.3f}}}\n\\newcommand{{\\RtWorstHi}}{{{worst[2][2]:.3f}}}\n\\newcommand{{\\RtOtherHiMax}}{{{second:.3f}}}\n")
    fh.write(f"\\newcommand{{\\RbTwoAllMin}}{{{s3(min(out['two'][m][0] for m in out['two']))}}}\n\\newcommand{{\\RbTwoAllMax}}{{{s3(max(out['two'][m][0] for m in out['two']))}}}\n")
print("worst RB round trip:", worst, "| next largest upper bound:", round(second, 3))
