"""Write figs/recast_numbers.tex: every number quoted in the recast text, from saved results."""
import json, pathlib
H = pathlib.Path(__file__).resolve().parent
N = json.load(open(H / "figs" / "numbers.json")); S, T = N["models"], N["tests"]
probe = json.load(open(H / "probe_results.json")); rt = json.load(open(H / "roundtrip_results.json"))
def tl(m):
    ev = [json.loads(l) for l in open(H / "results" / f"train_log_{m}.jsonl")]
    d = next(e for e in ev if e["event"] == "data"); done = next(e for e in ev if e["event"] == "done")
    return d, done
out = {}
f3 = lambda v: f"{v:.3f}"; s3 = lambda v: f"{v:+.3f}".replace("-", "$-$")
def ci(name, x):
    out[name] = s3(x[0]); out[name + "Lo"] = s3(x[1]); out[name + "Hi"] = s3(x[2])
for m, tag in [("tarteel", "Tar"), ("M0", "Mz"), ("M1", "Mo"), ("M2", "Mt")]:
    out[f"Clean{tag}"] = f3(S[m]["clean"][0])
    ci(f"Pv{tag}", S[m]["pv"]); ci(f"Rb{tag}", S[m]["rb"])
    out[f"RtPvG{tag}"] = f3(S[m]["rt_pv_g"][0]); out[f"RtPvL{tag}"] = f3(S[m]["rt_pv_l"][0])
    out[f"RtRbG{tag}"] = f3(S[m]["rt_rb_g"][0]); out[f"RtRbL{tag}"] = f3(S[m]["rt_rb_l"][0])
mods = ["tarteel", "M0", "M1", "M2"]
out["RbMin"] = f3(min(S[m]["rb"][0] for m in mods)); out["RbMax"] = f3(max(S[m]["rb"][0] for m in mods))
out["RtPvGMin"] = f"{min(S[m]['rt_pv_g'][0] for m in mods):.2f}"; out["RtPvGMax"] = f"{max(S[m]['rt_pv_g'][0] for m in mods):.2f}"
out["RtPvLMin"] = f"{min(S[m]['rt_pv_l'][0] for m in mods):.2f}"; out["RtPvLMax"] = f"{max(S[m]['rt_pv_l'][0] for m in mods):.2f}"
out["RtRbMax"] = f"{max(max(S[m]['rt_rb_g'][0], S[m]['rt_rb_l'][0]) for m in mods):.3f}"
for k in ("E1", "E2", "E4"):
    ci(f"Test{k.replace('1','One').replace('2','Two').replace('4','Four')}", T[k])
out["AucPv"] = f3(probe["global@4"]["auc_M2member_vs_M1"]); out["AucPvLo"] = f3(probe["global@4"]["ci95"][0]); out["AucPvHi"] = f3(probe["global@4"]["ci95"][1])
out["AucRb"] = f3(probe["global_rb@4"]["auc_M2member_vs_M1"]); out["ProbeN"] = str(probe["global@4"]["n"])
out["OvershootMt"] = s3(rt["M2"]["corrected_0.5"][2][0]); out["OvershootMtLo"] = s3(rt["M2"]["corrected_0.5"][2][1][0]); out["OvershootMtHi"] = s3(rt["M2"]["corrected_0.5"][2][1][1])
for m, tag in [("M0", "Mz"), ("M1", "Mo"), ("M2", "Mt")]:
    d, done = tl(m)
    out[f"Train{tag}"] = f"{d['train']:,}".replace(",", "{,}"); out[f"Val{tag}"] = f"{done['best_val_wer']:.3f}"
    out[f"Spk{tag}"] = str(d.get("train_reciters"))
out["DroppedEval"] = str(tl("M1")[0]["dropped_eval_rows"])
lines = ["% Generated by exposure/make_macros.py from saved results; do not edit by hand."]
lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in out.items()]
(H / "figs" / "recast_numbers.tex").write_text("\n".join(lines) + "\n")
print(len(out), "macros"); print("\n".join(lines[1:12]))

# ---- k=2 PV contrast (CUDA runs, paper crossed bootstrap) and device check ----
import collections, sys
import numpy as np
sys.path.insert(0, str(H.parent / "confirmation")); sys.argv = ["x"]
import analyze_confirmation as A
P = ["Alafasy", "Sudais", "Shuraym", "Dussary", "Rifai"]
def rows(path, recs=P):
    d = collections.defaultdict(dict)
    for l in open(path):
        r = json.loads(l)
        if r["kind"] == "condition" and r["reciter"] in recs:
            d[(r["reciter"], r["verse"])][(r["arm"], r["k"])] = r["whisper"]["wer"]
    return d
extra = {}
for m, tag in [("tarteel", "Tar"), ("M0", "Mz"), ("M1", "Mo"), ("M2", "Mt")]:
    d = rows(H / "results" / m / "observations.jsonl")
    prim = {n: {"verses": [], "differences": []} for n in P}
    for (n, v), row in sorted(d.items()):
        if ("nucleus", 2.0) in row and ("global", 2.0) in row:
            prim[n]["verses"].append(v); prim[n]["differences"].append(row[("nucleus", 2.0)] - row[("global", 2.0)])
    s = A.crossed_summary(prim, np.random.default_rng(A.SEED))
    extra[f"PvTwo{tag}"] = s3(s["mean"])
cu = rows(H / "cuda_check" / "observations.jsonl", ["Rifai"]); mac = rows(H.parent / "confirmation" / "results" / "observations.jsonl", ["Rifai"])
keys = [(k, a) for k in cu for a in cu[k] if k in mac and a in mac[k]]
extra["DevRows"] = str(len(keys)); extra["DevSame"] = str(sum(abs(cu[k][a] - mac[k][a]) < 1e-9 for k, a in keys))
gap = lambda d: np.mean([row[("nucleus", 4.0)] - row[("global", 4.0)] for row in d.values() if ("nucleus", 4.0) in row and ("global", 4.0) in row])
extra["DevGapDiff"] = f"{abs(gap(cu) - gap(mac)):.3f}"
with open(H / "figs" / "recast_numbers.tex", "a") as fh:
    fh.write("\n".join(f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in extra.items()) + "\n")
print(extra)

# ---- global RB k=4 WER per model (for the robustness sentence) ----
g = {}
for m, tag in [("tarteel", "Tar"), ("M0", "Mz"), ("M1", "Mo"), ("M2", "Mt")]:
    d = rows(H / "results" / m / "observations.jsonl")
    per = [np.mean([row[("global_rb", 4.0)] for (n, v), row in d.items() if n == r and ("global_rb", 4.0) in row]) for r in P]
    g[tag] = float(np.mean(per))
own = [g["Mz"], g["Mo"], g["Mt"]]
with open(H / "figs" / "recast_numbers.tex", "a") as fh:
    fh.write(f"\\newcommand{{\\GlobRbTar}}{{{g['Tar']:.3f}}}\n\\newcommand{{\\GlobRbOwnMin}}{{{min(own):.2f}}}\n\\newcommand{{\\GlobRbOwnMax}}{{{max(own):.2f}}}\n")
print(g)

# ---- k=2 PV round trip (explains the sign flip) and per-reciter RB consistency ----
two_g, two_l, pos, cells = [], [], 0, 0
for m in ["tarteel", "M0", "M1", "M2"]:
    d = rows(H / "results" / m / "observations.jsonl")
    rt = rows(H / "results" / f"rt_{m}" / "observations.jsonl")
    for key, row in rt.items():
        d[key].update(row)
    gl, lo = [], []
    for n in P:
        gl.append(np.mean([r[("global_rt", 2.0)] - r[("sham_pv_global", 1.0)] for (rc, v), r in d.items() if rc == n and ("global_rt", 2.0) in r]))
        lo.append(np.mean([r[("nucleus_rt", 2.0)] - r[("sham_pv_local", 1.0)] for (rc, v), r in d.items() if rc == n and ("nucleus_rt", 2.0) in r]))
        c = np.mean([r[("nucleus_rb", 4.0)] - r[("global_rb", 4.0)] for (rc, v), r in d.items() if rc == n and ("nucleus_rb", 4.0) in r and ("global_rb", 4.0) in r])
        pos += c > 0; cells += 1
    two_g.append(np.mean(gl)); two_l.append(np.mean(lo))
with open(H / "figs" / "recast_numbers.tex", "a") as fh:
    fh.write(f"\\newcommand{{\\RtTwoGMin}}{{{min(two_g):.2f}}}\n\\newcommand{{\\RtTwoGMax}}{{{max(two_g):.2f}}}\n"
             f"\\newcommand{{\\RtTwoLMin}}{{{min(two_l):.2f}}}\n\\newcommand{{\\RtTwoLMax}}{{{max(two_l):.2f}}}\n"
             f"\\newcommand{{\\RbCellsPos}}{{{pos}}}\n\\newcommand{{\\RbCells}}{{{cells}}}\n")
print("k2 global", [round(x, 3) for x in two_g], "local", [round(x, 3) for x in two_l], "RB positive cells", pos, "/", cells)
